version: "3.6"
services:
    
    frontend:
        container_name: frontend
        image: ganadara135/abbfront:latest
        ports:
            - 80:80
        networks:
            - abb-net
        env_file:
            - .env
        environment:
            - CHOKIDAR_USEPOLLING=true  # hot-reloading work
            - REACT_APP_SERVER_PORT=${REACT_APP_SERVER_PORT}        
            - REACT_APP_SERVER_URL=${REACT_APP_SERVER_URL}

# volumes:
#     rdb-data:
networks:
    abb-net:
        name: abb-net